//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

== Installing Components [[camel-installing]]

Camel comes with almost 200 components, so you can imagine that we don't install all of them by default.  This section shows you how
to find available components and how to install them at runtime.

=== List available components

Camel components are available as installable features.  You can look at the full list of available features using the
_feature:list_ command, using _grep_ to limit things down to features related to Camel:

[source,text,subs="attributes"]
----
karaf@root> feature:list | grep camel
camel-xmlsecurity     | {camel-version}      |          | Uninstalled | camel-{camel-version}  |
camel-xmpp            | {camel-version}      |          | Uninstalled | camel-{camel-version}  |
camel-xstream         | {camel-version}      | x        | Started     | camel-{camel-version}  |
camel-yammer          | {camel-version}      |          | Uninstalled | camel-{camel-version}  |
camel-zipfile         | {camel-version}      |          | Uninstalled | camel-{camel-version}  |
----

=== Install and uninstalling components

You can use _feature:install_ to install any component on the list.

An example: to install the _camel-cache_ component
[source,text]
----
karaf@root> feature:install camel-cache
----

Similarly, you can also uninstall components that you're no longer using with _feature:uninstall_
[source,text]
----
karaf@root> feature:uninstall camel-cache
----
